### ISSUE TITLE
Language -Tools 

### ISSUE THREAD

**Issue by rohitgodspeed** [godspeedsystems/language-tools#34]
This task is created to display all the work which id done and which suppose to done in next tasks, i will also mentioned tasks which related to language tools, so that this is the main language tools dashboard everything related to the language tools is here.

Child issues
- snippets for all inbuilt tasks. 
- creation of plugins events like kafka event  snippets
- On starting if language tools it will check the version of godspeed core
- create a snippets of sample data model of prisma

## What to do 
To build an extension that create and make autocomplete the specific words like body , response , body - this will pop out automatically. 
```
  params:
    - name: name_one
      in: query
      required: false
      description: Detailed description of the Params
```
## How to do it 
- To build and extension and create a snippets that when user type some word related to that particular snippet then extension will suggest to user that snippet, if the user approves then it will directly shown to the editor.

### Snippets we should prepare 
 - **Event Snippet**
     - when user type 
- If user type `Godspeed Event` in the src/event (path) file then it will give you some sample data to make an event.

- In the Event Snippets contains the event string , authn , summary, description, fn, on_validation_error, sample params, sample body, responses. After creating an Event you can configure the code with your requirements For Ex. Changing the body, params , responses. You can change the values by pressing up and down arrow and tab or Enter to move next.

- If user type `Godspeed Workflow` in the src/workflow (path) then it will give a snippet of sample workflow which includes summary, description, id, tasks, fn and args.

##### Mandatory Fiels

- There are some key-value pairs in the event and workflows, which needs to be filled to get a proper output, below are the examples of it.

#### In Event

- There are few key-value pairs which are important to the workflow, those are mandatory in the event.

  - For params - 

    - names , in 

    ```
      params:
        - name: world
          in: query
          required: true
    ```
- For Body - 

    - content , application/json, schema, type

    ```
    body:
      description: This is the Description of body
      required: false
      content:
        application/json:
          schema:
            type: string
    ```
- For responses - 
    - 200, content, application/json schema, type
###### In Workflow 

  - in the Workflow there are some key-value pairs that are important to make good workflows.

  - tasks , id, fn , args 

  - in the few built in tasks there are keys like `cases` in  [com.gs.switch]and `conditions` in com.gs.if_else , `values` in com.gs.each_sequential are the mandatory keys.

### Rules

- Minimun length of the description and summary is 50 letters and minimum length is 2.
- To define an Id in the Workflow id should be all in small letters , without spaces, without numbers and minimum charactors is 2 and maximum length is 45
- Minimum length of the summary and description are 2 and maximum length is 50
